# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASDKShowCase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASDKShowCase
  pod 'TLIndexPathTools'
  pod 'pop'
  pod 'SnapKit', '~>3.2.0'
  pod 'AsyncDisplayKit', '~>2.0'
  pod 'Atributika', '~>3.1'
end
